version: '2'

services:
    php-fpm:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        volumes:
            - ./:/app:cached
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    nginx:
        image: nginx:1.11
        ports:
            - "8080:80"
        volumes_from:
            - php-fpm
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    mariadb:
        image: mariadb:10
        ports:
            - "33060:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=app
